-- Run this in Supabase SQL Editor.
-- Stores reports with creator (user_id) so each report is traceable.

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  category text not null,
  location text not null,
  description text not null,
  status text not null default 'submitted',
  created_at timestamptz not null default now()
);

alter table public.reports enable row level security;

drop policy if exists "Users can insert own reports" on public.reports;
create policy "Users can insert own reports"
  on public.reports
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Authenticated users can read reports" on public.reports;
drop policy if exists "Users can read own reports" on public.reports;
create policy "Authenticated users can read reports"
  on public.reports
  for select
  using (auth.uid() is not null);

